In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"

from diffusers import AutoencoderKLMochi
from mochi_pipeline import MochiPipeline, linear_quadratic_schedule, retrieve_timesteps
from transformers import T5EncoderModel, T5Tokenizer
from mochi_processor import MochiAttnProcessor2_0
import torch
import torchvision
from pathlib import Path

def encode_videos(model: torch.nn.Module, vid_path: Path):
    video, _, metadata = torchvision.io.read_video(str(vid_path), output_format="THWC", pts_unit="secs")
    video = video.permute(3, 0, 1, 2)
    og_shape = video.shape
    print(f"Original video shape: {og_shape}")
    video = video.unsqueeze(0)
    video = video.float() / 127.5 - 1.0
    video = video.to(model.device)

    assert video.ndim == 5

    with torch.inference_mode():
        with torch.autocast("cuda", dtype=torch.bfloat16):
            ldist = model._encode(video)

    return ldist


/home/wg25r/miniconda/envs/mochi/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model_id = "genmo/mochi-1-preview"
pipeline = MochiPipeline.from_pretrained(model_id, torch_dtype=torch.float16)

pipeline.enable_vae_slicing()
pipeline.enable_vae_tiling()
pipeline.to("cuda")


Loading pipeline components...: 100%|██████████| 5/5 [00:03<00:00,  1.27it/s]


MochiPipeline {
  "_class_name": "MochiPipeline",
  "_diffusers_version": "0.34.0.dev0",
  "_name_or_path": "genmo/mochi-1-preview",
  "force_zeros_for_empty_prompt": false,
  "scheduler": [
    "diffusers",
    "FlowMatchEulerDiscreteScheduler"
  ],
  "text_encoder": [
    "transformers",
    "T5EncoderModel"
  ],
  "tokenizer": [
    "transformers",
    "T5Tokenizer"
  ],
  "transformer": [
    "diffusers",
    "MochiTransformer3DModel"
  ],
  "vae": [
    "diffusers",
    "AutoencoderKLMochi"
  ]
}

In [3]:
video = "/home/wg25r/make_it_move/training_free/finetrainers/training/mochi-1/dataset/moth.mp4"
lattent = encode_videos(
    pipeline.vae,
    Path(video),
)

/home/wg25r/miniconda/envs/mochi/lib/python3.11/site-packages/torchvision/io/_video_deprecation_warning.py:5: UserWarning: The video decoding and encoding capabilities of torchvision are deprecated from version 0.22 and will be removed in version 0.24. We recommend that you migrate to TorchCodec, where we'll consolidate the future decoding/encoding capabilities of PyTorch: https://github.com/pytorch/torchcodec
  warnings.warn(


Original video shape: torch.Size([3, 0, 1, 1])


RuntimeError: Expected 4D or 5D (batch mode) tensor with possibly 0 batch size and other non-zero dimensions for input, but got: [1, 64, 0, 1, 1]

In [ ]:
noise = torch.randn_like(lattent) * 0.1
noisy_latent = lattent * 0.5 + noise * 0.5

In [ ]:
import numpy as np
tokenizer = pipeline.tokenizer
prompt = "a camflagued *animal* hiding in the +background+"
positive_start_index = tokenizer.tokenize(prompt).index("▁*")
positive_end_index = tokenizer.tokenize(prompt).index("*")

negative_start_index = tokenizer.tokenize(prompt).index("▁+")
negative_end_index = tokenizer.tokenize(prompt).index("+")

print(tokenizer.tokenize(prompt))


indices = torch.tensor(list(range(positive_start_index + 1, positive_end_index)) + list(range(negative_start_index + 1, negative_end_index)))# + 1 # plus one because of the <extra_id_0> token
print(indices)
positive_mask = torch.tensor([1] * (positive_end_index - positive_start_index - 1) + [0] * (negative_end_index - negative_start_index - 1))
negative_mask = torch.tensor([0] * (positive_end_index - positive_start_index - 1) + [1] * (negative_end_index - negative_start_index - 1))
print(positive_mask)
print(negative_mask)

threshold_noise = 0.025
sigmas = linear_quadratic_schedule(20, threshold_noise)
sigmas = np.array(sigmas)
timesteps = retrieve_timesteps(
            pipeline.scheduler,
            num_inference_steps=20,
            device="cuda",
            timesteps=None,
            sigmas=sigmas,
        )

for block in pipeline.transformer.transformer_blocks:
    block.attn1.processor = MochiAttnProcessor2_0(token_index_of_interest=indices, positive_mask=positive_mask) 

['▁', 'a', '▁cam', 'f', 'la', 'gue', 'd', '▁*', 'anim', 'al', '*', '▁hiding', '▁in', '▁the', '▁+', 'back', 'ground', '+']
tensor([ 8,  9, 15, 16])
tensor([1, 1, 0, 0])
tensor([0, 0, 1, 1])


In [ ]:
timesteps

(tensor([  0.0000,   2.5000,   5.0000,   7.5000,  10.0000,  12.5000,  15.0000,
          17.5000,  20.0000,  22.5000,  25.0000,  37.0000,  68.0000, 118.0000,
         187.0000, 275.0000, 382.0000, 508.0000, 653.0000, 817.0001],
        device='cuda:0'),
 20)

In [ ]:
from diffusers.utils import export_to_video

video = pipeline(latents=noisy_latent.cuda()[:,:12],
         timesteps=timesteps[0][-7:].cpu(),
         prompt=prompt, 
         emphasize_indices=(0,0),
         emphasize_neg_indices=(0,0),
)

(0, 0)


100%|██████████| 7/7 [00:39<00:00,  5.64s/it]


In [1]:
export_to_video(np.array(video["frames"])[0], "output.mp4")

NameError: name 'export_to_video' is not defined

In [ ]:
frames = torchvision.io.read_video(str("/home/wg25r/make_it_move/training_free/finetrainers/training/mochi-1/dataset/crab_000.mp4"), output_format="THWC", pts_unit="secs")[0]
extracted_positive_maps = [] 
extracted_negative_maps = []
maps = pipeline.attention_maps  
for step in range(max(len(maps) - 10, 0), len(maps)-1):
    for layer in range(len(maps[step])): 
        # print(maps[step][layer].shape)# [B, H, K, Q]
        map = maps[step][layer][0].mean(0)[0] # use sum, because in it it was softmax and spread outed
        # print(maps[step][layer][0].mean(0)[positive_mask==1].shape) # need to use bool!
        extracted_positive_maps.append(map.cpu().float().numpy().reshape(-1, frames[0].shape[0]//16, frames[0].shape[1]//16))
        
        map = maps[step][layer][0].mean(0)[1]
        extracted_negative_maps.append(map.cpu().float().numpy().reshape(-1, frames[0].shape[0]//16, frames[0].shape[1]//16))

        # assert torch.all(maps[step][layer][0].mean(0).sum(0) >= 0.99), maps[step][layer][0].mean(0).sum(0)
extracted_positive_maps = np.array(extracted_positive_maps)
extracted_negative_maps = np.array(extracted_negative_maps)
np.isnan(extracted_positive_maps).any()

/home/wg25r/miniconda/envs/mochi/lib/python3.11/site-packages/torchvision/io/_video_deprecation_warning.py:5: UserWarning: The video decoding and encoding capabilities of torchvision are deprecated from version 0.22 and will be removed in version 0.24. We recommend that you migrate to TorchCodec, where we'll consolidate the future decoding/encoding capabilities of PyTorch: https://github.com/pytorch/torchcodec
  warnings.warn(
/home/wg25r/miniconda/envs/mochi/lib/python3.11/site-packages/torchvision/io/video.py:199: UserWarning: The pts_unit 'pts' gives wrong results. Please use pts_unit 'sec'.
  warnings.warn("The pts_unit 'pts' gives wrong results. Please use pts_unit 'sec'.")


np.True_

In [ ]:
import numpy as np
import math
file_id = 1
# %%
mask = (extracted_positive_maps > extracted_positive_maps.mean(axis=0) + extracted_positive_maps.std(axis=0)).astype(np.float32) + (extracted_positive_maps < extracted_positive_maps.mean(axis=0) - extracted_positive_maps.std(axis=0)).astype(np.float32)
mean_pos_map = np.nanmean(extracted_positive_maps, axis=0)


mask = (extracted_negative_maps > extracted_negative_maps.mean(axis=0) + extracted_negative_maps.std(axis=0)).astype(np.float32) + (extracted_negative_maps < extracted_negative_maps.mean(axis=0) - extracted_negative_maps.std(axis=0)).astype(np.float32)
mean_neg_map = np.nanmean(extracted_negative_maps, axis=0)

import cv2


def opening(x, kernel_size=3):
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (kernel_size, kernel_size))
    x = [cv2.morphologyEx(i, cv2.MORPH_OPEN, kernel) for i in x]
    return x

def blur(x, kernel_size=3):
    kernel = np.ones((kernel_size, kernel_size), np.float32) / (kernel_size * kernel_size)
    x = [cv2.filter2D(i, -1, kernel) for i in x]
    return x

def resize(x, size):
    return [cv2.resize(i, size) for i in x]
    
    
def normalize(x):
    return [(i - i.min()) / (i.max() - i.min()) for i in x]

def compose_frames(frames, maps):
    frames = [np.array(frame).astype(float)/255 for frame in frames]
    for i in range(len(frames)):
        map = cv2.cvtColor(maps[(i-2)//6], cv2.COLOR_GRAY2RGB).astype(float)       
        frames[i] = cv2.addWeighted(frames[i], 0.5, map, 0.5, 0)
    return frames

def repeat_maps(maps, total_len):
    export_maps = []
    for i in range(total_len):
        export_maps.append(maps[math.ceil((i-2)/6)])
    return export_maps

# print("a")
mean_pos_map = opening(mean_pos_map, kernel_size=3)
mean_neg_map = opening(mean_neg_map, kernel_size=3)
mean_pos_map = blur(mean_pos_map, kernel_size=3)
mean_neg_map = blur(mean_neg_map, kernel_size=3)
mean_pos_map = resize(mean_pos_map, size=(frames[0].shape[1], frames[0].shape[0]))
mean_neg_map = resize(mean_neg_map, size=(frames[0].shape[1], frames[0].shape[0]))

mean_pos_map = normalize(mean_pos_map)
mean_neg_map = normalize(mean_neg_map)

video = repeat_maps(mean_pos_map, len(frames))

# video = compose_frames(frames, mean_pos_map)
print(np.array(video).shape)
export_to_video(video, f"res/mochi_pos_{file_id:02d}_map.mp4", fps=30)

video = repeat_maps(mean_neg_map, len(frames))
# video = compose_frames(frames, mean_neg_map)
export_to_video(video, f"res/mochi_neg_{file_id:02d}_map.mp4", fps=30)

# fg = np.clip(np.array(mean_pos_map) - np.array(mean_neg_map), 0, 100)
fg = np.array(mean_pos_map) - np.array(mean_neg_map) * 2
fg[fg < 0] = 0
print(fg.max())

fg = normalize(fg)
video = compose_frames(frames, fg) 
export_to_video(video, f"map.mp4", fps=30)

(37, 480, 848)
1.0


/tmp/ipykernel_4065889/758690003.py:33: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  frames = [np.array(frame).astype(float)/255 for frame in frames]


'map.mp4'

In [ ]:
frames[0].shape, fg[0].shape

(torch.Size([480, 848, 3]), (480, 848))